---
title: "hw5"
output: github_document
date: "2025-11-11"
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(broom)
set.seed(1)

```


## Problem1

```{r}
# Function to simulate whether at least two people share a birthday
same_birthday <- function(n) {
  
  birthdays <- sample(1:365, size = n, replace = TRUE)
  
  has_duplicate <- any(duplicated(birthdays))
  
  # Step 3: Return TRUE if there is a shared birthday, FALSE otherwise
  return(has_duplicate)
}


set.seed(123)
n_sim <- 10000
group_sizes <- 2:50
prob_results <- numeric(length(group_sizes))

prob_results <- sapply(group_sizes, function(n) {
  mean(replicate(n_sim, same_birthday(n)))   # Average of TRUE/FALSE results
})


birthday_df <- data.frame(
  group_size = group_sizes,
  probability = prob_results
)

library(ggplot2)
ggplot(birthday_df, aes(x = group_size, y = probability)) +
  geom_line(color = "steelblue", size = 1.3) +
  geom_point(color = "darkred", size = 2) +
  labs(
    title = "Probability That at Least Two People Share a Birthday",
    subtitle = "10,000 simulations per group size (no leap years)",
    x = "Group Size (n)",
    y = "Probability"
  ) +
  theme_minimal(base_size = 14)
```

## Problem 2
```{r}
n <- 30
sigma <- 5
mu_vals <- 0:6
n_sim <- 5000

sim <- expand_grid(mu = mu_vals, iter = 1:n_sim) |>
  mutate(
    x = map(mu, ~ rnorm(n, .x, sigma)),
    t = map(x, ~ tidy(t.test(.x, mu = 0))),
    mu_hat = map_dbl(t, "estimate"),
    p = map_dbl(t, "p.value"),
    reject = p < 0.05
  )
```

```{r}
# power for each mu
power_df <- sim |> group_by(mu) |> summarize(power = mean(reject))

ggplot(power_df, aes(mu, power)) +
  geom_point() + geom_line() +
  labs(x = "True μ", y = "Power")

# average estimates
means_df <- sim |> group_by(mu) |> 
  summarize(
    avg_all = mean(mu_hat),
    avg_rej = mean(mu_hat[reject])
  )
ggplot(means_df, aes(mu)) +
  geom_line(aes(y = avg_all)) +
  geom_line(aes(y = avg_rej), color = "red") +
  geom_point(aes(y = avg_all)) +
  geom_point(aes(y = avg_rej), color = "red") +
  labs(x = "True μ", y = "Average µ̂",
       title = "Black = all samples, Red = rejected samples")
```
Effect size increases as mu increases. 
The sample and true mean are overall equal, although rejected mean are higher when true mean equals to 1.


## Problem 3

From the raw data, we have 7209 female, 40739 male, and 4231 people who didn't
disclose their sex.

```{r}
homi <- read_csv("homicide-data.csv")
homi |>
  count(victim_sex)
```


```{r}
homi_summary <- homi %>%
  mutate(
    city_state = paste(city, state, sep = ", "),
    unsolved = disposition %in% c("Closed without arrest", "Open/No arrest")
  ) %>%
  group_by(city_state) %>%
  summarize(
    total_homicides = n(),
    unsolved_homicides = sum(unsolved, na.rm = TRUE)
  )

homi_summary

```










